### ISSUE TITLE
I put you on BGG!

### ISSUE THREAD

**Issue by ElectricCoffee** [LucasBorboleta/jersi#1]
Hi Lucas, I just wanted to mention that I got your game onto BoardGameGeek!
With your permission, I'd like to upload the rules PDF and a photo of the game in action as well just to round out the page :)

Alternatively, you could do it youself if you like :)

You can find the page here: https://boardgamegeek.com/boardgame/369835/jersi

**Comment by LucasBorboleta** [comment]
Hi Niko ! 

 

This is very nice !

You have my permission to upload the rules PDF and a photo of the game in action.

 

Questions :

*	Are you a player of Jersi ? 
*	How did you got the motivation for registering Jersi and myself as author ?
*	I don’t understand the characteristics «  reimplements arimaa » that you mentionned about Jersi ; could you explain ?
*	Regarding « Print n Play », maybe I should create a « DIY.md » file that refers to the pictures to be used for actually crafting th game.
*	What about creating a « wiki » as for the « mikjersi » variant of « jersi » : https://github.com/LucasBorboleta/mikjersi/wiki .
*	Can I update myself the designer page ? I would like to use the same logo/picture that in github, and refer to my blog.

 

For your information : after « jersi » and « mikjersi », I have designed « pijersi », again a variant of « jersi » ; https://github.com/LucasBorboleta/pijersi

I think that « pijersi » reproduces the essence of « jersi », but which shorter games and less rules to be explained. 

 

Many thanks !

 

Cheers,

Lucas

 

De : Niko Lepka ***@***.***> 
Envoyé : dimanche 4 septembre 2022 23:00
À : LucasBorboleta/jersi ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [LucasBorboleta/jersi] I put you on BGG! (Issue #1)

 

Hi Lucas, I just wanted to mention that I got your game onto BoardGameGeek!
With your permission, I'd like to upload the rules PDF and a photo of the game in action as well just to round out the page :)

Alternatively, you could do it youself if you like :)

You can find the page here: https://boardgamegeek.com/boardgame/369835/jersi

**Comment by ElectricCoffee** [comment]
Hi again, I just want  to preface this by saying I don't have any control over how the game was added to BGG, all I did was submit the game to the database. Any administrator who later had their hands on the game added any and all inaccuracies are due to their involvement.

> Hi Niko ! This is very nice ! You have my permission to upload the rules PDF and a photo of the game in action. 

Thanks so much, I will do so :)

> Questions : 
> * Are you a player of Jersi ? 

No, not yet, I plan on making my own set in the next few weeks. I have access to a laser cutter at a maker space, which has been great for making games at will.

> * How did you got the motivation for registering Jersi and myself as author ? 

I'm big on board game preservation. I've created numerous rulebooks for other obscure games that went out of print years ago by gathering bits and pieces of information I could gather online, and putting it all into a PDF.
While yours isn't out of print, it is rather unknown, and I thought it be nice to add it to the database.
Hopefully some people will be able to find it and play it :)

> * I don’t understand the characteristics « reimplements arimaa » that you mentionned about Jersi ; could you explain ?

I did not add this, it must be one of the admins who did that. I will see to get this fixed asap.

> * Regarding « Print n Play », maybe I should create a « DIY.md » file that refers to the pictures to be used for actually crafting th game. 

You could definitely upload that as a file on BGG, yeah.

> * What about creating a « wiki » as for the « mikjersi » variant of « jersi » : https://github.com/LucasBorboleta/mikjersi/wiki . 

I don't know how to do that, I'm not an admin on BGG, I just submitted the game via their regular submission application.

> * Can I update myself the designer page ? I would like to use the same logo/picture that in github, and refer to my blog.
 
I think so. You need to be a member on BGG and then edit the designer page. An admin will then go ahead and approve the changes if need be. I think you can also get an admin to assign your account as the creator.

> For your information : after « jersi » and « mikjersi », I have designed « pijersi », again a variant of « jersi » ; https://github.com/LucasBorboleta/pijersi I think that « pijersi » reproduces the essence of « jersi », but which shorter games and less rules to be explained.

I will see what I can do

**Comment by LucasBorboleta** [comment]
Hi Niko !

 

All that sounds good ! Thanks for your answers and your willing to board game preservation !

I will monitor the « jersi » and « Lucas Borboleta » registration on BGG.

 

Regarding laser cutter and maybe engraver, for a while, I had the plan to make a jersi set using such tools.

Could you share some photo of your work, when you will be done (maybe from a web site/blog you have) ?

 

One of the issue that I tried to solve, was the engravement on « dark » cubes : to have the rock/paper/… marks well contrasted on dark cubes might be an issue.

A possible solution I saw by some youtuber (a girl by the way) is to put some sticker on the face to be engraved, then after the engravement doing some painting, and at the end only to remove the sticker.

 

Cheers,

Lucas

 

 

De : Niko Lepka ***@***.***> 
Envoyé : lundi 5 septembre 2022 09:17
À : LucasBorboleta/jersi ***@***.***>
Cc : Lucas Borboleta ***@***.***>; Comment ***@***.***>
Objet : Re: [LucasBorboleta/jersi] I put you on BGG! (Issue #1)

 

Hi again, I just want to preface this by saying I don't have any control over how the game was added to BGG, all I did was submit the game to the database. Any administrator who later had their hands on the game added any and all inaccuracies are due to their involvement.

Hi Niko ! This is very nice ! You have my permission to upload the rules PDF and a photo of the game in action.

Thanks so much, I will do so :)

Questions :

*	Are you a player of Jersi ?

No, not yet, I plan on making my own set in the next few weeks. I have access to a laser cutter at a maker space, which has been great for making games at will.

*	How did you got the motivation for registering Jersi and myself as author ?

I'm big on board game preservation. I've created numerous rulebooks for other obscure games that went out of print years ago by gathering bits and pieces of information I could gather online, and putting it all into a PDF.
While yours isn't out of print, it is rather unknown, and I thought it be nice to add it to the database.
Hopefully some people will be able to find it and play it :)

*	I don’t understand the characteristics « reimplements arimaa » that you mentionned about Jersi ; could you explain ?
I did not add this, it must be one of the admins who did that. I will see to get this fixed asap.

*	Regarding « Print n Play », maybe I should create a « DIY.md » file that refers to the pictures to be used for actually crafting th game.

You could definitely upload that as a file on BGG, yeah.

*	What about creating a « wiki » as for the « mikjersi » variant of « jersi » : https://github.com/LucasBorboleta/mikjersi/wiki .

I don't know how to do that, I'm not an admin on BGG, I just submitted the game via their regular submission application.

*	Can I update myself the designer page ? I would like to use the same logo/picture that in github, and refer to my blog.

I think so. You need to be a member on BGG and then edit the designer page. An admin will then go ahead and approve the changes if need be. I think you can also get an admin to assign your account as the creator.

For your information : after « jersi » and « mikjersi », I have designed « pijersi », again a variant of « jersi » ; https://github.com/LucasBorboleta/pijersi I think that « pijersi » reproduces the essence of « jersi », but which shorter games and less rules to be explained.

I will see what I can do

**Comment by ElectricCoffee** [comment]
> Regarding laser cutter and maybe engraver, for a while, I had the plan to make a jersi set using such tools.
> 
> Could you share some photo of your work, when you will be done (maybe from a web site/blog you have) ?

Yes, I'll send you a photo once I get it made. It could be a while though.

> One of the issue that I tried to solve, was the engravement on « dark » cubes : to have the rock/paper/… marks well contrasted on dark cubes might be an issue.
> 
> A possible solution I saw by some youtuber (a girl by the way) is to put some sticker on the face to be engraved, then after the engravement doing some painting, and at the end only to remove the sticker.

What I was going to do was to get a bunch of wooden dice, laser engrave all of them, and then stain the dark ones with some wood stain, then lacquer all of them, and then paint the markings with the appropriate colour.
